export enum CapacitacionActionTypes {
  FETCH_CAPACITACIONES_REQUEST = "FETCH_CAPACITACIONES_REQUEST",
  FETCH_CAPACITACIONES_SUCCESS = "FETCH_CAPACITACIONES_SUCCESS",
  FETCH_CAPACITACIONES_FAILURE = "FETCH_CAPACITACIONES_FAILURE",
  FETCH_CAPACITACIONES = "FETCH_CAPACITACIONES",

  ADD_CAPACITACION = "ADD_CAPACITACION",
  REMOVE_CAPACITACION = "REMOVE_CAPACITACION",
}
